"""Tests for the MCP server tool functions."""

import json
import pytest
from pathlib import Path

import openacr_mcp.server as srv
from openacr_mcp.acr_client import AcrClient

OPENACR_DIR = Path.home() / "openacr"
skip_no_openacr = pytest.mark.skipif(
    not (OPENACR_DIR / "bin" / "acr").exists(),
    reason="OpenACR not installed at ~/openacr",
)


@skip_no_openacr
class TestServerTools:
    """Integration tests that call tool functions directly (not via MCP protocol)."""

    @pytest.fixture(autouse=True)
    def setup_client(self):
        """Initialize the global client for tool functions."""
        srv._client = AcrClient(OPENACR_DIR)
        yield
        srv._client = None

    def test_list_namespaces(self):
        result = json.loads(srv.list_namespaces())
        assert result["ok"] is True
        assert result["count"] > 0
        ns_names = [r["ns"] for r in result["records"]]
        assert "algo" in ns_names

    def test_list_ctypes(self):
        result = json.loads(srv.list_ctypes("algo"))
        assert result["ok"] is True
        assert result["count"] > 0

    def test_get_ctype(self):
        result = json.loads(srv.get_ctype("algo.Bool"))
        assert result["ok"] is True
        assert "algo.Bool" in result["tree"]

    def test_list_fields(self):
        result = json.loads(srv.list_fields("algo.Bool"))
        assert result["ok"] is True
        assert result["count"] >= 1

    def test_query(self):
        result = json.loads(srv.query("dmmeta.ns:algo"))
        assert result["ok"] is True
        assert result["count"] == 1

    def test_search(self):
        result = json.loads(srv.search("Bool"))
        assert result["ctype_count"] > 0 or result["field_count"] > 0

    def test_list_generated_headers(self):
        result = json.loads(srv.list_generated_headers("algo"))
        assert result["count"] >= 1
        assert any("algo_gen.h" in h for h in result["headers"])

    def test_get_generated_code(self):
        result = json.loads(srv.get_generated_code("include/gen/algo_gen.h"))
        assert "content" in result
        assert "Generated by AMC" in result["content"]

    def test_get_generated_code_not_found(self):
        result = json.loads(srv.get_generated_code("include/gen/nonexistent_gen.h"))
        assert "error" in result

    def test_get_functions(self):
        result = json.loads(srv.get_functions("algo"))
        assert result["total_enums"] > 0
        assert result["total_structs"] > 0
        assert result["total_functions"] > 0

    def test_get_functions_unknown_ns(self):
        result = json.loads(srv.get_functions("nonexistent"))
        assert "error" in result


class TestServerToolsNoClient:
    """Test that tools handle missing client gracefully."""

    @pytest.fixture(autouse=True)
    def clear_client(self):
        srv._client = None
        yield

    def test_list_namespaces_no_client(self):
        result = json.loads(srv.list_namespaces())
        assert "error" in result

    def test_query_no_client(self):
        result = json.loads(srv.query("dmmeta.ns:%"))
        assert "error" in result
