"""Tests for the MCP server tool functions."""

import json
from unittest.mock import patch, MagicMock
import pytest
from pathlib import Path

import openacr_mcp.server as srv
from openacr_mcp.acr_client import AcrClient, AcrResult

OPENACR_DIR = Path.home() / "openacr"
skip_no_openacr = pytest.mark.skipif(
    not (OPENACR_DIR / "bin" / "acr").exists(),
    reason="OpenACR not installed at ~/openacr",
)


@skip_no_openacr
class TestServerTools:
    """Integration tests that call tool functions directly (not via MCP protocol)."""

    @pytest.fixture(autouse=True)
    def setup_client(self):
        """Initialize the global client for tool functions."""
        srv._client = AcrClient(OPENACR_DIR)
        yield
        srv._client = None

    def test_list_namespaces(self):
        result = json.loads(srv.list_namespaces())
        assert result["ok"] is True
        assert result["count"] > 0
        ns_names = [r["ns"] for r in result["records"]]
        assert "algo" in ns_names

    def test_list_ctypes(self):
        result = json.loads(srv.list_ctypes("algo"))
        assert result["ok"] is True
        assert result["count"] > 0

    def test_get_ctype(self):
        result = json.loads(srv.get_ctype("algo.Bool"))
        assert result["ok"] is True
        assert "algo.Bool" in result["tree"]

    def test_list_fields(self):
        result = json.loads(srv.list_fields("algo.Bool"))
        assert result["ok"] is True
        assert result["count"] >= 1

    def test_query(self):
        result = json.loads(srv.query("dmmeta.ns:algo"))
        assert result["ok"] is True
        assert result["count"] == 1

    def test_search(self):
        result = json.loads(srv.search("Bool"))
        assert result["ctype_count"] > 0 or result["field_count"] > 0

    def test_list_generated_headers(self):
        result = json.loads(srv.list_generated_headers("algo"))
        assert result["count"] >= 1
        assert any("algo_gen.h" in h for h in result["headers"])

    def test_get_generated_code(self):
        result = json.loads(srv.get_generated_code("include/gen/algo_gen.h"))
        assert "content" in result
        assert "Generated by AMC" in result["content"]

    def test_get_generated_code_not_found(self):
        result = json.loads(srv.get_generated_code("include/gen/nonexistent_gen.h"))
        assert "error" in result

    def test_get_functions(self):
        result = json.loads(srv.get_functions("algo"))
        assert result["total_enums"] > 0
        assert result["total_structs"] > 0
        assert result["total_functions"] > 0

    def test_get_functions_unknown_ns(self):
        result = json.loads(srv.get_functions("nonexistent"))
        assert "error" in result


class TestServerToolsNoClient:
    """Test that tools handle missing client gracefully."""

    @pytest.fixture(autouse=True)
    def clear_client(self):
        srv._client = None
        yield

    def test_list_namespaces_no_client(self):
        result = json.loads(srv.list_namespaces())
        assert "error" in result

    def test_query_no_client(self):
        result = json.loads(srv.query("dmmeta.ns:%"))
        assert "error" in result

    def test_create_target_no_client(self):
        result = json.loads(srv.create_target("test", "ssimdb"))
        assert "error" in result


class TestGetWorkflowGuide:
    """Tests for the get_workflow_guide tool (no client needed)."""

    def test_returns_valid_json(self):
        result = json.loads(srv.get_workflow_guide())
        assert "workflows" in result
        assert "arg_types_reference" in result
        assert "reftype_reference" in result

    def test_has_expected_workflow_sections(self):
        result = json.loads(srv.get_workflow_guide())
        titles = [w["title"] for w in result["workflows"]]
        assert "Create a new ssimdb with types" in titles
        assert "Add an enum type" in titles
        assert "Create a struct with foreign key references" in titles
        assert "Create an exe that uses a ssimdb" in titles

    def test_arg_types_has_categories(self):
        result = json.loads(srv.get_workflow_guide())
        arg_types = result["arg_types_reference"]
        assert "strings" in arg_types
        assert "integers" in arg_types
        assert "other" in arg_types
        assert "algo.cstring" in arg_types["strings"]
        assert "u32" in arg_types["integers"]

    def test_reftype_reference_has_key_types(self):
        result = json.loads(srv.get_workflow_guide())
        reftypes = result["reftype_reference"]
        assert "Val" in reftypes
        assert "Pkey" in reftypes
        assert "Base" in reftypes
        assert "Thash" in reftypes

    def test_each_workflow_has_steps(self):
        result = json.loads(srv.get_workflow_guide())
        for workflow in result["workflows"]:
            assert "title" in workflow
            assert "steps" in workflow
            assert len(workflow["steps"]) >= 2


class TestCreateTarget:
    """Unit tests for create_target tool (mocked client)."""

    @pytest.fixture(autouse=True)
    def setup_mock_client(self):
        mock_client = MagicMock(spec=AcrClient)
        srv._client = mock_client
        self.mock_client = mock_client
        yield
        srv._client = None

    def test_calls_acr_ed_create_target(self):
        self.mock_client.acr_ed_create_target.return_value = AcrResult(ok=True)
        result = json.loads(srv.create_target("mydb", "ssimdb", "My database"))
        assert result["ok"] is True
        self.mock_client.acr_ed_create_target.assert_called_once_with(
            "mydb", "ssimdb", "My database"
        )

    def test_rejects_invalid_nstype(self):
        result = json.loads(srv.create_target("mydb", "invalid_type"))
        assert "error" in result
        assert "invalid_type" in result["error"]
        self.mock_client.acr_ed_create_target.assert_not_called()

    def test_valid_nstypes(self):
        for nstype in ("ssimdb", "exe", "lib", "protocol"):
            self.mock_client.acr_ed_create_target.return_value = AcrResult(ok=True)
            result = json.loads(srv.create_target("test", nstype))
            assert result["ok"] is True

    def test_propagates_error(self):
        self.mock_client.acr_ed_create_target.return_value = AcrResult(
            ok=False, stderr="namespace already exists", returncode=1
        )
        result = json.loads(srv.create_target("algo", "ssimdb"))
        assert result["ok"] is False
        assert "error" in result


class TestCamelToSnake:
    """Tests for the _camel_to_snake helper."""

    def test_simple(self):
        assert srv._camel_to_snake("Genre") == "genre"

    def test_two_words(self):
        assert srv._camel_to_snake("ReadingStatus") == "reading_status"

    def test_three_words(self):
        assert srv._camel_to_snake("OrderLineItem") == "order_line_item"

    def test_already_lower(self):
        assert srv._camel_to_snake("status") == "status"

    def test_acronym(self):
        assert srv._camel_to_snake("HTMLParser") == "html_parser"


class TestCreateCtypeAutoSsimfile:
    """Unit tests for create_ctype's auto-ssimfile behavior."""

    @pytest.fixture(autouse=True)
    def setup_mock_client(self):
        mock_client = MagicMock(spec=AcrClient)
        srv._client = mock_client
        self.mock_client = mock_client
        yield
        srv._client = None

    def test_ssimdb_auto_creates_ssimfile(self):
        self.mock_client.acr_ed_create.return_value = AcrResult(ok=True)
        self.mock_client.get_ns_type.return_value = "ssimdb"
        self.mock_client.acr_insert.return_value = AcrResult(ok=True)
        self.mock_client.amc.return_value = AcrResult(ok=True)

        result = json.loads(srv.create_ctype("mydb", "MyRecord", "A record"))
        assert result["ok"] is True
        assert result["ssimfile_auto_created"] is True

        # Verify ssimfile was inserted with correct snake_case name
        self.mock_client.acr_insert.assert_called_once_with(
            "dmmeta.ssimfile  ssimfile:mydb.my_record  ctype:mydb.MyRecord"
        )
        # Verify amc was re-run
        self.mock_client.amc.assert_called_once()

    def test_ssimdb_camel_case_conversion(self):
        self.mock_client.acr_ed_create.return_value = AcrResult(ok=True)
        self.mock_client.get_ns_type.return_value = "ssimdb"
        self.mock_client.acr_insert.return_value = AcrResult(ok=True)
        self.mock_client.amc.return_value = AcrResult(ok=True)

        srv.create_ctype("mydb", "ReadingStatus")

        self.mock_client.acr_insert.assert_called_once_with(
            "dmmeta.ssimfile  ssimfile:mydb.reading_status  ctype:mydb.ReadingStatus"
        )

    def test_exe_namespace_no_ssimfile(self):
        self.mock_client.acr_ed_create.return_value = AcrResult(ok=True)
        self.mock_client.get_ns_type.return_value = "exe"

        result = json.loads(srv.create_ctype("myapp", "Config"))
        assert result["ok"] is True
        self.mock_client.acr_insert.assert_not_called()

    def test_ssimfile_insert_failure(self):
        self.mock_client.acr_ed_create.return_value = AcrResult(ok=True)
        self.mock_client.get_ns_type.return_value = "ssimdb"
        self.mock_client.acr_insert.return_value = AcrResult(
            ok=False, stderr="duplicate record", returncode=1
        )

        result = json.loads(srv.create_ctype("mydb", "Dup"))
        assert "error" in result
        assert "ssimfile insert failed" in result["error"]


class TestCreateFconstUnit:
    """Unit tests for create_fconst using acr_insert."""

    @pytest.fixture(autouse=True)
    def setup_mock_client(self):
        mock_client = MagicMock(spec=AcrClient)
        srv._client = mock_client
        self.mock_client = mock_client
        yield
        srv._client = None

    def test_calls_acr_insert(self):
        self.mock_client.acr_insert.return_value = AcrResult(ok=True)
        result = json.loads(srv.create_fconst("mydb.Status.status", "active", "Active"))
        assert result["ok"] is True
        assert result["fconst"] == "mydb.Status.status/active"
        self.mock_client.acr_insert.assert_called_once()
        call_arg = self.mock_client.acr_insert.call_args[0][0]
        assert "fconst:mydb.Status.status/active" in call_arg

    def test_propagates_error(self):
        self.mock_client.acr_insert.return_value = AcrResult(
            ok=False, stderr="field not found", returncode=1
        )
        result = json.loads(srv.create_fconst("bad.Field.x", "val"))
        assert result["ok"] is False
        assert "error" in result


@skip_no_openacr
class TestGetUsageExamples:
    """Integration tests for get_usage_examples tool."""

    @pytest.fixture(autouse=True)
    def setup_client(self):
        srv._client = AcrClient(OPENACR_DIR)
        yield
        srv._client = None

    def test_returns_valid_json(self):
        result = json.loads(srv.get_usage_examples("bookdb"))
        assert result["namespace"] == "bookdb"
        assert "include" in result
        assert "bookdb_gen.h" in result["include"]
        assert len(result["types"]) > 0

    def test_enum_has_code_examples(self):
        result = json.loads(srv.get_usage_examples("bookdb"))
        enums = [t for t in result["types"] if t["is_enum"]]
        assert len(enums) > 0
        genre = next((t for t in enums if t["type_name"] == "Genre"), None)
        assert genre is not None
        assert len(genre["code"]) >= 2
        assert len(genre["enum_values"]) >= 2
        # Check code contains GetEnum / SetEnum / ToCstr patterns
        all_code = " ".join(c["cpp"] for c in genre["code"])
        assert "GetEnum" in all_code
        assert "SetEnum" in all_code
        assert "ToCstr" in all_code

    def test_struct_has_code_examples(self):
        result = json.loads(srv.get_usage_examples("bookdb"))
        structs = [t for t in result["types"] if not t["is_enum"]]
        assert len(structs) > 0
        book = next((t for t in structs if t["type_name"] == "Book"), None)
        assert book is not None
        assert len(book["code"]) >= 2
        assert "fields" in book
        # Check code contains Init and field assignment
        all_code = " ".join(c["cpp"] for c in book["code"])
        assert "Book_Init" in all_code
        assert "rec." in all_code

    def test_struct_fk_fields_shown(self):
        result = json.loads(srv.get_usage_examples("bookdb"))
        book = next((t for t in result["types"] if t["type_name"] == "Book"), None)
        assert book is not None
        # FK fields should show "FK to" in the code
        create_code = book["code"][0]["cpp"]
        assert "FK to" in create_code

    def test_unknown_namespace(self):
        result = json.loads(srv.get_usage_examples("nonexistent_ns"))
        assert "error" in result

    def test_skips_internal_types(self):
        result = json.loads(srv.get_usage_examples("bookdb"))
        type_names = [t["type_name"] for t in result["types"]]
        assert "FieldId" not in type_names
        assert not any(n.endswith("Case") for n in type_names)
